import 'money.dart';

/// Immutable representation of external evidence linked to an [EconomicEvent].
///
/// ### Forensic Fingerprint vs. Canonical Identity Material
/// SpendX 2.0 strictly distinguishes two tiers of evidence identity:
///
/// 1. **Forensic Fingerprint ([bodyFingerprint])**:
///    - Cryptographic SHA-256 hash of the normalized incoming message body.
///    - Used to identify exact raw payload duplicates when incoming messages arrive.
///    - **CRITICAL**: The system does NOT define `bodyFingerprint == complete future identity`.
///      A fingerprint alone cannot reconstruct missing accounting facts or match
///      events from heterogeneous sources (e.g., cross-matching SMS with bank CSV).
///
/// 2. **Canonical Identity Material (Retained indefinitely after 30-day purge)**:
///    - [sourceType]: Evidence origin ('sms', 'ocr', 'csv_import', 'bank_api').
///    - [sourceIdentifier]: Origin address/sender (e.g. 'VM-HDFCBK').
///    - [sourceTimestamp]: External physical transaction timestamp.
///    - [extractedAmount]: Canonical monetary value and currency ([Money]).
///    - [extractedMerchant]: Normalized merchant/counterparty name.
///    - [externalReference]: Bank reference, UTR, UPI transaction ID, or bill reference.
///    - [accountContext]: Card/Account hint (e.g. last 4 digits 'XX1234') where available.
///
/// When the raw encrypted payload ([rawPayloadEncrypted]) is erased after 30 days
/// by [purgeRawPayload], all Canonical Identity Material and the [bodyFingerprint]
/// survive intact.
class Evidence {
  /// Unique identifier of the evidence record.
  final String id;

  /// External evidence origin ('sms', 'ocr', 'csv_import', 'manual', 'bank_api').
  final String sourceType;

  /// Origin address / identifier (e.g., Bank SMS shortcode 'VM-HDFCBK', receipt file name).
  final String? sourceIdentifier;

  /// When the evidence was generated by the external source.
  final DateTime sourceTimestamp;

  /// Cryptographic SHA-256 hash of the normalized source body for forensic auditing.
  final String? bodyFingerprint;

  /// Parsed monetary amount extracted from the source evidence.
  final Money? extractedAmount;

  /// Merchant or counterparty name extracted from the evidence.
  final String? extractedMerchant;

  /// Unique external reference number (e.g. UTR, Bank Ref No, Invoice number).
  final String? externalReference;

  /// Card or account context hint (e.g. 'XX4092' or 'A/c *1234') parsed from evidence.
  final String? accountContext;

  /// Encrypted raw message body payload. Subject to 30-day retention purge.
  final String? rawPayloadEncrypted;

  /// Timestamp after which [rawPayloadEncrypted] must be permanently erased.
  final DateTime? retentionExpiresAt;

  /// Whether the raw payload has been purged in accordance with retention policy.
  final bool isPayloadPurged;

  /// Optional ID of the canonical [EconomicEvent] this evidence supports.
  final String? economicEventId;

  /// When this evidence record was created in SpendX.
  final DateTime createdAt;

  const Evidence({
    required this.id,
    required this.sourceType,
    this.sourceIdentifier,
    required this.sourceTimestamp,
    this.bodyFingerprint,
    this.extractedAmount,
    this.extractedMerchant,
    this.externalReference,
    this.accountContext,
    this.rawPayloadEncrypted,
    this.retentionExpiresAt,
    this.isPayloadPurged = false,
    this.economicEventId,
    required this.createdAt,
  });

  /// Creates a new [Evidence] with the raw encrypted body purged,
  /// preserving all forensic fingerprints, timestamps, and extracted facts.
  Evidence purgeRawPayload() {
    return Evidence(
      id: id,
      sourceType: sourceType,
      sourceIdentifier: sourceIdentifier,
      sourceTimestamp: sourceTimestamp,
      bodyFingerprint: bodyFingerprint,
      extractedAmount: extractedAmount,
      extractedMerchant: extractedMerchant,
      externalReference: externalReference,
      accountContext: accountContext,
      rawPayloadEncrypted: null,
      retentionExpiresAt: retentionExpiresAt,
      isPayloadPurged: true,
      economicEventId: economicEventId,
      createdAt: createdAt,
    );
  }

  /// Links this evidence to a confirmed [EconomicEvent].
  Evidence linkToEvent(String eventId) {
    return Evidence(
      id: id,
      sourceType: sourceType,
      sourceIdentifier: sourceIdentifier,
      sourceTimestamp: sourceTimestamp,
      bodyFingerprint: bodyFingerprint,
      extractedAmount: extractedAmount,
      extractedMerchant: extractedMerchant,
      externalReference: externalReference,
      accountContext: accountContext,
      rawPayloadEncrypted: rawPayloadEncrypted,
      retentionExpiresAt: retentionExpiresAt,
      isPayloadPurged: isPayloadPurged,
      economicEventId: eventId,
      createdAt: createdAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Evidence &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceType == other.sourceType &&
          sourceIdentifier == other.sourceIdentifier &&
          sourceTimestamp == other.sourceTimestamp &&
          bodyFingerprint == other.bodyFingerprint &&
          externalReference == other.externalReference &&
          accountContext == other.accountContext &&
          isPayloadPurged == other.isPayloadPurged &&
          economicEventId == other.economicEventId;

  @override
  int get hashCode => Object.hash(
        id,
        sourceType,
        sourceIdentifier,
        sourceTimestamp,
        bodyFingerprint,
        externalReference,
        accountContext,
        isPayloadPurged,
        economicEventId,
      );

  @override
  String toString() =>
      'Evidence(id: $id, src: $sourceType, ref: $externalReference, ctx: $accountContext, purged: $isPayloadPurged)';
}
