name: spend_x
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0+15

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.4
  uuid: ^4.5.3
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  csv: ^7.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_generative_ai: ^0.4.7
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.0
  collection: ^1.19.0
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.1
  http: ^1.6.0
  provider: ^6.1.5+1
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.1
  flutter_dotenv: ^6.0.0
  google_sign_in: 6.2.1
  googleapis: ^16.0.0
  workmanager: ^0.9.0
  games_services: ^5.0.0

  extension_google_sign_in_as_googleapis_auth: 2.0.13
  flutter_secure_storage: ^10.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2
  connectivity_plus: ^7.0.0
  crypto: ^3.0.6
  cryptography: ^2.7.0
  archive: ^4.0.2
  receive_sharing_intent: ^1.8.1
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.svg"
  min_sdk_android: 21
  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: "assets/logo.svg"
  adaptive_icon_monochrome: "assets/logo.svg"
  adaptive_icon_foreground_padding: 16

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.svg
    - assets/fonts/
