import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../salary_ledger/salary_ledger_models.dart';
import '../../salary_ledger/salary_ledger_notifier.dart';

/// Format currency for PDF (use Rs. since Helvetica lacks ₹ glyph)
String _pdfCurrency(double value) {
  final formatted = NumberFormat.currency(symbol: 'Rs.', decimalDigits: 2).format(value);
  return formatted;
}

/// Generates and shares a PDF salary report for the currently selected company.
Future<void> exportSalaryPDF(SalaryLedgerState state,
    {List<SalaryMonthView>? filteredMonths}) async {
  final company = state.selectedCompany;
  final months = filteredMonths ?? state.months;
  final health = state.health;
  final report = generateReport(months);

  final pdf = pw.Document(
    title: '${company?.name ?? "Salary"} Report',
    author: 'SpendX',
  );

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(36),
      header: (context) => _buildHeader(company?.name ?? 'Salary Report'),
      footer: (context) => _buildFooter(context),
      build: (context) => [
        _buildKpiSection(report),
        pw.SizedBox(height: 20),
        if (health.totalMonths > 0) ...[
          _buildReliabilitySection(health),
          pw.SizedBox(height: 20),
        ],
        _buildMonthlyTable(months),
      ],
    ),
  );

  final bytes = await pdf.save();
  final safeName = (company?.name ?? 'salary')
      .replaceAll(RegExp(r'[^\w]'), '_')
      .toLowerCase();
  await Printing.sharePdf(bytes: bytes, filename: '${safeName}_report.pdf');
}

pw.Widget _buildHeader(String companyName) {
  return pw.Container(
    padding: const pw.EdgeInsets.only(bottom: 12),
    decoration: const pw.BoxDecoration(
      border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.blueGrey200, width: 1)),
    ),
    child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          companyName,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blueGrey900,
          ),
        ),
        pw.Text(
          'Salary Report',
          style: pw.TextStyle(
            fontSize: 12,
            color: PdfColors.blueGrey500,
          ),
        ),
      ],
    ),
  );
}

pw.Widget _buildFooter(pw.Context context) {
  return pw.Container(
    padding: const pw.EdgeInsets.only(top: 8),
    decoration: const pw.BoxDecoration(
      border: pw.Border(
          top: pw.BorderSide(color: PdfColors.blueGrey200, width: 0.5)),
    ),
    child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by SpendX · ${DateFormat('dd MMM yyyy').format(DateTime.now())}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.blueGrey400),
        ),
        pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.blueGrey400),
        ),
      ],
    ),
  );
}

pw.Widget _buildKpiSection(SalaryReport report) {
  return pw.Row(
    children: [
      _kpiBox('Total Earned', _pdfCurrency(report.totalPaid),
          PdfColors.green700),
      pw.SizedBox(width: 12),
      _kpiBox(
          'Pending', _pdfCurrency(report.pending), PdfColors.orange700),
      pw.SizedBox(width: 12),
      _kpiBox(
          'Total Bonus', _pdfCurrency(report.totalBonus), PdfColors.purple700),
      pw.SizedBox(width: 12),
      _kpiBox('Avg Delay',
          '${report.avgDelay.toStringAsFixed(1)} days', PdfColors.red700),
    ],
  );
}

pw.Widget _kpiBox(String label, String value, PdfColor color) {
  return pw.Expanded(
    child: pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: PdfColors.grey300),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style: const pw.TextStyle(
                  fontSize: 9, color: PdfColors.blueGrey500)),
          pw.SizedBox(height: 4),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: color)),
        ],
      ),
    ),
  );
}

pw.Widget _buildReliabilitySection(CompanyHealth health) {
  final scoreColor = health.reliabilityScore >= 80
      ? PdfColors.green700
      : health.reliabilityScore >= 50
          ? PdfColors.orange700
          : PdfColors.red700;

  return pw.Container(
    padding: const pw.EdgeInsets.all(12),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey50,
      borderRadius: pw.BorderRadius.circular(6),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Employer Reliability',
                style: pw.TextStyle(
                    fontSize: 12, fontWeight: pw.FontWeight.bold)),
            pw.Text(
              '${health.reliabilityScore.toStringAsFixed(0)}%',
              style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: scoreColor),
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Row(
          children: [
            _reliabilityStat('On-Time',
                '${health.onTimePercent.toStringAsFixed(0)}%'),
            _reliabilityStat('Avg Delay', '${health.avgDelayDays} days'),
            _reliabilityStat('Late Months', '${health.lateMonths}'),
            _reliabilityStat('Longest Streak', '${health.longestDelayStreak}'),
          ],
        ),
      ],
    ),
  );
}

pw.Widget _reliabilityStat(String label, String value) {
  return pw.Expanded(
    child: pw.Column(
      children: [
        pw.Text(value,
            style:
                pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 2),
        pw.Text(label,
            style:
                const pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey400)),
      ],
    ),
  );
}

pw.Widget _buildMonthlyTable(List<SalaryMonthView> months) {
  final headers = [
    'Month',
    'Expected',
    'Paid',
    'Bonus',
    'Remaining',
    'Status',
    'Delay',
  ];

  final rows = months.map((m) {
    final monthDate = DateTime.tryParse('${m.month.month}-01');
    final label =
        monthDate != null ? DateFormat('MMM yyyy').format(monthDate) : m.month.month;
    return [
      label,
      _pdfCurrency(m.month.expectedAmount),
      _pdfCurrency(m.salaryPaid),
      m.bonusTotal > 0 ? _pdfCurrency(m.bonusTotal) : '-',
      _pdfCurrency(m.remaining),
      m.status.label,
      m.delayDays > 0 ? '${m.delayDays}d' : '-',
    ];
  }).toList();

  return pw.TableHelper.fromTextArray(
    headers: headers,
    data: rows,
    headerStyle: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        fontSize: 9,
        color: PdfColors.white),
    headerDecoration:
        const pw.BoxDecoration(color: PdfColors.blueGrey700),
    cellStyle: const pw.TextStyle(fontSize: 9),
    oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
    cellPadding:
        const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
    columnWidths: {
      0: const pw.FlexColumnWidth(2),
      1: const pw.FlexColumnWidth(1.8),
      2: const pw.FlexColumnWidth(1.8),
      3: const pw.FlexColumnWidth(1.5),
      4: const pw.FlexColumnWidth(1.8),
      5: const pw.FlexColumnWidth(1.2),
      6: const pw.FlexColumnWidth(0.9),
    },
    cellAlignments: {
      0: pw.Alignment.centerLeft,
      1: pw.Alignment.centerRight,
      2: pw.Alignment.centerRight,
      3: pw.Alignment.centerRight,
      4: pw.Alignment.centerRight,
      5: pw.Alignment.center,
      6: pw.Alignment.center,
    },
  );
}
